perf: control the nested display of related files for vscode
easy-temps/vue3-vant-mobile pull request #134
Opened 2024-11-19 09:32 UTC by ChunyuPCY

When you add this code, some files that look like folders collapse other related files

2024-11-19 09:49 UTC, ljt990218 commented
能看看不加此代码时，你的项目目录结构嘛

> When you add this code, some files that look like folders collapse other related files

2024-11-19 09:49 UTC, ljt990218 commented
我这边加上 反而更不简洁了

2024-11-19 09:57 UTC, ChunyuPCY commented
> 能看看不加此代码时，你的项目目录结构嘛
> 
> > When you add this code, some files that look like folders collapse other related files



> 能看看不加此代码时，你的项目目录结构嘛
> 
> > When you add this code, some files that look like folders collapse other related files

<img width="309" alt="截屏2024-11-19 17 55 35" src="https://github.com/user-attachments/assets/d318817d-f603-4b72-bd81-c41ae07c42ec">

这个是我的项目结构。可能是需要比较新的 VSCode 版本吧

2024-11-19 12:34 UTC, CharleeWa commented
VS Code 的 [file nesting feature](https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting)  需要 v1.67。

2024-11-19 13:04 UTC, CharleeWa requested changes
感谢 PR！ 不过我建议使用  antfu 的 `vscode-file-nesting-config` 配置，这个预设更完整，而且会定期自动更新以支持新的文件类型。

一个潜在问题，文件嵌套可能会让新手一时找不到某些文件。所以，我觉得可以让开发者主动选择是否使用 - 自己安装的话，开发者更可能知道在做什么。不强制使用，毕竟不同开发者可能有不同的偏好。

我们在 `.vscode/extensions.json` 当中，补充如下扩展插件：

```json
{
  "recommendations": [
    "... existing code ..."
    "antfu.file-nesting"
  ]
}

```

开发者安装后，会在全局（用户设置）自动更新文件嵌套规则，无需在项目里面维护，非常方便。 @ljt990218 @ChunyuPCY  你们觉得如何？

2024-11-20 00:44 UTC, ChunyuPCY commented
> 感谢 PR！ 不过我建议使用 antfu 的 `vscode-file-nesting-config` 配置，这个预设更完整，而且会定期自动更新以支持新的文件类型。
> 
> 一个潜在问题，文件嵌套可能会让新手一时找不到某些文件。所以，我觉得可以让开发者主动选择是否使用 - 自己安装的话，开发者更可能知道在做什么。不强制使用，毕竟不同开发者可能有不同的偏好。
> 
> 我们在 `.vscode/extensions.json` 当中，补充如下扩展插件：
> 
> ```json
> {
>   "recommendations": [
>     "... existing code ..."
>     "antfu.file-nesting"
>   ]
> }
> ```
> 
> 开发者安装后，会在全局（用户设置）自动更新文件嵌套规则，无需在项目里面维护，非常方便。
> 
> @ljt990218 @ChunyuPCY 你们觉得如何？

托尼老师出品，必是精品，确实挺好的

2024-11-20 01:17 UTC, CharleeWa commented
@ChunyuPCY 可以补充一个提交吗？😄

2024-11-20 01:36 UTC, ChunyuPCY commented
> @ChunyuPCY 可以补充一个提交吗？😄

好的

2024-11-20 01:36 UTC, closed without merging